version: '3.8'

services:
  neo4j:
    # modified from: https://github.com/neo4j-examples/nlp-knowledge-graph/blob/master/docker-compose.yml
    image: neo4j:4.4.9-enterprise
    container_name: "vector-db"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4J_dbms_memory_pagecache_size=4G
      # - NEO4j_dbms_memory_heap_initial__size=4G
      # - NEO4J_dbms_memory_heap_max__size=8G
      # !!! GDS plugin was manually downloaded (2.1.6) and added to plugins = https://neo4j.com/download-center/
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - neo_net

  python:
    container_name: "python-env"
    # image was previously built with docker build -t pydev .
    # NOTE:  it is also possible to build the image with `build: .` instead of `image:` like below
    build: .
    # to have the shell open (e.g. --it in docker run)
    # https://stackoverflow.com/a/39150040
    stdin_open: true
    tty: true
    # map the project repo to the working directory created by the image
    volumes:
      - .:/brock/
    networks:
      - neo_net


networks:
  neo_net:
